"""One-time authoring utility. Outputs are ordinary editable source HTML."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]
def put(path, text):
    p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True)
    if p.exists():raise ValueError('Refusing to overwrite existing article: '+path)
    p.write_text(text.strip()+'\n',encoding='utf-8')
def cards(text, label='Cards'):
    names={'A':'Ace','K':'King','Q':'Queen','J':'Jack','T':'Ten','9':'Nine','8':'Eight','7':'Seven','6':'Six','5':'Five','4':'Four','3':'Three','2':'Two'}
    suits={'h':('hearts','♥'),'d':('diamonds','♦'),'c':('clubs','♣'),'s':('spades','♠')}
    out=[]
    for c in text.split():
        suit,symbol=suits[c[1]];cls=' is-red' if c[1] in 'hd' else ''
        out.append(f'<span class="reader-playing-card{cls}" role="img" aria-label="{names[c[0]]} of {suit}">{"10" if c[0]=="T" else c[0]}<small aria-hidden="true">{symbol}</small></span>')
    return '<div class="reader-cards" role="group" aria-label="'+escape(label)+'">'+''.join(out)+'</div>'
def reveal(label, body):
    return f'<details class="poker-details workshop-question lab-answer"><summary>{label}</summary><div>{body}</div></details>'
def begin(n, intro, scope):
    return f'''<article class="section folio-row viewer-guide" aria-labelledby="lab-intro">
<div class="section-meta"><p class="section-label">Decision Lab / {n:02d}</p></div>
<div class="section-content prose">
<nav class="viewer-breadcrumb" aria-label="Decision Lab breadcrumb"><a href="/poker/decision-labs/">All Decision Labs</a></nav>
<p class="viewer-scope">After-play study. {scope} All cards and action are fictional, not a personal hand or a solver recommendation.</p>
<h2 id="lab-intro">{intro}</h2>'''
def end(refs):
    return '<div class="viewer-sources"><h2>References and limits</h2><p>'+refs+' The scene and arithmetic are independently constructed. Prepared with AI assistance. No real hand, personal result or optimal strategy is claimed.</p></div></div></article>'

turn_answer='''<p>The turn is the <strong>four of hearts</strong>.</p>'''+cards('9h 7h 2c 4h','Board after the turn')+'''<p>A now has an ace-high flush: ace, jack, nine, seven and four of hearts. B still has three nines. A has moved ahead, but one river remains.</p><p>For the next exercise, suppose all betting is complete and both hands are tabled. The remaining river is guaranteed without another payment. Do not use this face-up calculation to justify an earlier call against an unknown range.</p>'''
losses='9s 7c 7d 7s 2h 2d 2s 4c 4d 4s'
count_answer='''<p>There are <strong>44 possible river cards</strong>: 52 minus four hole cards and four board cards. B wins on <strong>10</strong> of them, A wins on <strong>34</strong>, and there are <strong>no ties</strong>.</p>
<table class="viewer-table"><caption>Rivers that beat A's flush, with both hands known</caption><thead><tr><th scope="col">River rank</th><th scope="col">Cards left</th><th scope="col">B's best hand</th></tr></thead><tbody><tr><th scope="row">Nine</th><td>1</td><td>Four nines</td></tr><tr><th scope="row">Seven</th><td>3</td><td>Nines full of sevens</td></tr><tr><th scope="row">Two</th><td>3</td><td>Nines full of twos</td></tr><tr><th scope="row">Four</th><td>3</td><td>Nines full of fours</td></tr></tbody></table>
<p>The ten physical cards are:</p>'''+cards(losses,'Ten winning rivers for player B')+'''<p>B's exact chance is <strong>10 / 44 = 22.7%</strong>, rounded. A's is <strong>34 / 44 = 77.3%</strong>. These are conditional showdown probabilities for the known hands, not measured opponent tendencies or a tournament-prize calculation.</p><p>Why not divide by 46? In a hero-only turn view, six cards are known. Here the opponent's two cards are also exposed, so eight cards are known. The information set determines the denominator. The calculation assumes a fair remaining deck and no other known dead cards.</p>'''
river_answer='<p>The river is the <strong>two of diamonds</strong>.</p>'+cards('9h 7h 2c 4h 2d','Complete board')+'''<p>A still has an ace-high flush. B now makes a full house: nine of clubs, nine of diamonds, nine of hearts, two of clubs and two of diamonds. <strong>B wins.</strong></p><p>A did not lose because the flush became a weaker flush. A lost because B made a higher-ranked type of hand. An improvement on the turn is not a promise about the river.</p>'''
heart_answer='''<p><strong>The two of hearts also makes B a full house.</strong> It is one of the ten losing rivers for A, even though it puts another heart on the board. Count what the card does to both hands, not merely which suit appears.</p><p>A rule such as “another heart is good for the flush” is not enough. On this exact turn, A already has a flush. Pairing the board can change the winner. The rank of a card and its suit can carry different consequences.</p>'''
changed_answer='''<p>With B holding <strong>nine of clubs and seven of clubs</strong> on the same turn, B has two pair rather than a set. The remaining two nines and two sevens make a full house. That is <strong>4 / 44 = 9.1%</strong>, rounded. The other 40 rivers leave A ahead, with no ties.</p><p>A two or four now only creates a lower paired board for B; it does not supply a full house. The slogan “the board might pair” was too broad. Changing the opponent's hand changed which paired-board rivers actually matter.</p>'''
flush=begin(2,'The draw arrives. The hand is not over.','A face-up replay about runouts. Opponent cards are shown for explanation, not treated as information available during ordinary betting.')+'''
<p>A completed draw is an obvious turning point in a poker video. It can also hide the next question: what can still change? Follow the hand one street at a time, then count every possible river from the turn snapshot.</p>
<div class="reader-feature"><p class="reader-eyebrow">The cast / Both hands shown</p><div class="lab-hand-grid"><div><h3>Player A</h3>'''+cards('Ah Jh','Player A: ace and jack of hearts')+'''</div><div><h3>Player B</h3>'''+cards('9c 9d','Player B: two nines')+'''</div></div><p>Start on the flop. Do not reveal the turn until you can describe both hands.</p></div>
<section class="reader-case-step" aria-labelledby="flop-question"><h2 id="flop-question">01 / Read the flop</h2>'''+cards('9h 7h 2c','Flop: nine of hearts, seven of hearts, two of clubs')+'''<p>B has three nines. A has four hearts across the hole cards and board, not a completed flush. B is ahead now. That is different from being guaranteed to win.</p><p><strong>Before revealing:</strong> name a kind of turn card that could put A ahead. Keep a description of the current hand separate from a probability of eventually winning.</p>'''+reveal('Reveal the turn',turn_answer)+'''</section>
<section class="reader-case-step" aria-labelledby="river-count"><h2 id="river-count">02 / Count the ways back</h2><p>Continue after opening the turn. Both hands are exposed and one river remains. Which exact ranks could let B beat the flush? Count physical cards, not just rank names.</p>'''+reveal('Reveal the remaining-card count',count_answer)+'''</section>
<section class="reader-case-step" aria-labelledby="river-reveal"><h2 id="river-reveal">03 / Deal the last card</h2><p>Before opening the river, say what the best hand is <em>now</em> and what type of hand could overtake it. Neither statement needs the eventual result.</p>'''+reveal('Reveal the river and showdown',river_answer)+reveal('Check a different river: what about another heart?',heart_answer)+'''</section>
<section class="reader-case-step" aria-labelledby="changed-hand"><h2 id="changed-hand">04 / Change one input</h2><p>Return to the turn with the four of hearts on the board. Keep A's cards fixed, but change B's hand to the <strong>nine of clubs and seven of clubs</strong>. How many rivers now beat A's flush?</p>'''+reveal('Reveal the changed-hand answer',changed_answer)+'''</section>
<section class="reader-case-step" aria-labelledby="replay-output"><h2 id="replay-output">05 / Explain the swing without rewriting it</h2><p>A useful fictional voiceover is: “The heart moved A ahead. With both hands exposed, ten of the forty-four possible rivers would still beat the flush. This river was one of them.” It explains the changing situation without calling the result inevitable or impossible.</p><p>For your own review, save three items: cards known at the decision, cards that change the winner, and whether another bet must be paid before seeing them. A correct runout count does not by itself establish whether an earlier bet or call was good.</p><p><a href="/poker/pot-odds-workshop/#draws">Draws and future payments</a> explains that last distinction. The <a href="/poker/reading-the-board/">board-reading guide</a> gives a broader vocabulary for what can change.</p></section>
'''+end('<a href="https://www.pokerstars.com/poker/games/rules/hand-rankings/full-house/">PokerStars: full houses</a> explains why a full house beats a flush in standard hold’em. The displayed river counts are checked against all 44 remaining physical cards, not copied from a draw shortcut.')
flush=flush.replace('<article class=', '<article data-case-a="Ah Jh" data-case-b="9c 9d" data-case-alt-b="9c 7c" data-case-board="9h 7h 2c 4h 2d" data-case-losing="9s 7c 7d 7s 2h 2d 2s 4c 4d 4s" class=',1)
put('_source/poker/flush-and-redraw.html',flush)

pot_answer='''<p>Return the unmatched <strong>11 BB</strong> to C first. With A able to contribute six and B fourteen, nobody can contest C's chips above fourteen.</p><div class="lab-pot-layers"><div><span class="reader-eyebrow">Main pot / A, B and C</span><strong>18 BB</strong><p>6 + 6 + 6. All three players are eligible.</p></div><div><span class="reader-eyebrow">Side pot / B and C only</span><strong>16 BB</strong><p>8 + 8. A cannot win this pot.</p></div><div><span class="reader-eyebrow">Uncalled / Returned to C</span><strong>11 BB</strong><p>25 − 14. This is a refund, not a pot.</p></div></div><p><strong>18 + 16 + 11 = 45 BB.</strong> The contested pots total 34 BB. Saying “a 45-blind pot” would incorrectly include the returned chips.</p><p>A's main-pot eligibility is limited by the amount matched at A's contribution level. It is not a discount ticket to every chip that deeper players put forward.</p>'''
showdown='<p>The complete board is:</p>'+cards('Ac Ks 2d 7h 3c','Showdown board')+'''<p>A makes three aces. B makes three kings. C has a pair of queens. A has the strongest hand, but the pots still need separate awards.</p><p><strong>Main pot: A receives 18 BB.</strong> Among the three eligible hands, three aces wins. <strong>Side pot: B receives 16 BB.</strong> Only B and C are eligible, and three kings beats a pair of queens. C retains the eleven-blind refund.</p>'''
ledger='''<table class="viewer-table"><caption>Final chips, with the refund counted exactly once</caption><thead><tr><th scope="col">Player</th><th scope="col">Started with</th><th scope="col">Ends with</th><th scope="col">Net change</th></tr></thead><tbody><tr><th scope="row">A</th><td>6 BB</td><td>18 BB</td><td>+12 BB</td></tr><tr><th scope="row">B</th><td>14 BB</td><td>16 BB</td><td>+2 BB</td></tr><tr><th scope="row">C</th><td>25 BB</td><td>11 BB</td><td>−14 BB</td></tr></tbody></table><p>B loses the main pot to A but finishes two blinds ahead overall. C announced all-in but is not eliminated because eleven blinds were uncalled and returned. <strong>18 + 16 + 11 = 45 BB</strong> remains true after the awards, and the net changes sum to zero.</p><p>“All-in” describes an action; it does not tell you how many chips were ultimately matched. “Lost to A” describes one comparison; it does not tell you the outcome of every pot.</p>'''
variant='''<p>For contributions of <strong>4, 10 and 16 BB</strong>, the main pot is 4 × 3 = <strong>12 BB</strong>; the side pot is (10 − 4) × 2 = <strong>12 BB</strong>; and the refund is 16 − 10 = <strong>6 BB</strong>.</p><p>Keeping the same hand ranking, A receives twelve, B receives twelve, and C keeps six. The final stacks sum to the starting total of thirty. B again finishes two blinds ahead. Recalculate from the layers instead of memorizing the first example's totals.</p>'''
side=begin(3,'The best hand does not win every chip.','A three-handed, no-ante hold’em example about contribution levels, pot eligibility and refunds.')+'''
<p>Three players announce all-in. One player has the best hand, another wins the side pot, and the deepest stack gets uncalled chips back. To follow the result, the viewer needs more than a single pot total.</p><p>This case is about settlement, not whether the shoves were strategically good. There are no deductions, bounties, additional players or earlier pots outside the contributions described here.</p>
<div class="reader-feature"><p class="reader-eyebrow">Starting stacks / Before posting</p><div class="lab-hand-grid lab-three-hands"><div><h3>A / Button</h3><p>6 BB</p>'''+cards('Ah Ad','Player A: two aces')+'''</div><div><h3>B / Small blind</h3><p>14 BB</p>'''+cards('Kc Kd','Player B: two kings')+'''</div><div><h3>C / Big blind</h3><p>25 BB</p>'''+cards('Qh Qs','Player C: two queens')+'''</div></div><p>The cards are shown for this fictional replay. The board is revealed later.</p></div>
<section class="reader-case-step" aria-labelledby="all-in-action"><h2 id="all-in-action">01 / Follow the money once</h2><p>The blinds are 0.5 / 1 BB. A shoves to six. B goes all-in to fourteen. C moves the full twenty-five forward. A and B have no more chips to match anything above fourteen.</p><p>The totals <strong>6, 14 and 25 BB already include the blinds</strong> where applicable. B adds 13.5 beyond the small blind; C moves 24 beyond the big blind. Do not add those blinds again.</p><p><strong>Before revealing:</strong> separate the 45 BB moved forward into money all three can win, money only two can win, and money that was never matched.</p>'''+reveal('Reveal the pot layers',pot_answer)+'''</section>
<section class="reader-case-step" aria-labelledby="eligible-winners"><h2 id="eligible-winners">02 / Award each pot separately</h2><p>Once the pots are separated, name the eligible players before comparing cards. A can win only the main pot. B and C contest both pots. The refund already belongs to C regardless of the board.</p>'''+reveal('Reveal the board and award the pots',showdown)+'''</section>
<section class="reader-case-step" aria-labelledby="final-ledger"><h2 id="final-ledger">03 / Check the whole result</h2><p>How many chips does each player finish with? Can a player lose to the strongest hand and still gain chips? Does the deepest player actually bust?</p>'''+reveal('Reveal the final stacks and net changes',ledger)+'''</section>
<section class="reader-case-step" aria-labelledby="change-stacks"><h2 id="change-stacks">04 / Change the stack sizes</h2><p>Use the same order of hand strengths, but suppose A moves four blinds, B ten and C sixteen. There are still no other chips or deductions. Rebuild the two pots and refund before opening the answer.</p>'''+reveal('Reveal the smaller-stack calculation',variant)+'''</section>
<section class="reader-case-step" aria-labelledby="side-pot-story"><h2 id="side-pot-story">05 / Make the graphic tell the right story</h2><p>Use separate on-screen labels for the main pot, side pot and refund. Keep the eligibility beside the amount: “Main 18 BB: A/B/C” and “Side 16 BB: B/C.” Do not animate returned chips as a showdown win.</p><p>A short narration can say: “A wins the main pot with three aces. B beats C for the side pot, so B still gains two blinds. C keeps the eleven blinds nobody called.” That gives the audience the complete result without an elaborate explanation of every chip.</p><p>The same layers matter in a study calculation. A short stack's call price must be compared with pots the player is eligible to win, not someone else's side pot. The <a href="/poker/betting-and-pots/">bets and side-pots guide</a> covers the underlying bookkeeping, and the <a href="/poker/hand-to-vlog/#graphics">graphics workbench</a> explains how to keep it readable.</p></section>
'''+end('<a href="https://www.pokerstars.com/poker/games/rules/">PokerStars rules</a> explains table stakes and side-pot eligibility. The displayed amounts are a fictional no-ante, no-deduction example; consult the event’s rules for actual procedures.')
side=side.replace('<article class=', '<article data-case-a="Ah Ad" data-case-b="Kc Kd" data-case-c="Qh Qs" data-case-board="Ac Ks 2d 7h 3c" data-case-contributions="6 14 25" class=',1)
put('_source/poker/side-pot-lab.html',side)

hub='''<section class="section folio-row" aria-labelledby="labs-intro"><div class="section-meta"><p class="section-label">Pause / Predict / Reveal</p></div><div class="section-content">
<h2 class="intro" id="labs-intro">Put yourself at the decision, not just the result.</h2><p class="section-deck">Three visual, fictional cases. Work out one thing before opening the next panel: the price, the cards that change the winner, or which player can win which chips.</p><p class="reader-help">For after-play study and poker viewers. No account, answer submission or live-play assistance. The panels work without JavaScript.</p>
<div class="lab-series-grid" role="group" aria-label="Choose a Decision Lab">
<article class="lab-series-card"><p class="reader-eyebrow">01 / Read the range</p><h3><a href="/poker/decision-lab/">One river. Two different stories.</a></h3>'''+cards('As Qc','Lab 01 focal hand')+'''<p>A river call can win or lose without changing what was known beforehand. Price the call, change the bluff weighting, then compare two endings.</p><p class="lab-skill"><strong>Leave with:</strong> a conditional decision explanation that survives either result.</p></article>
<article class="lab-series-card"><p class="reader-eyebrow">02 / Read the runout</p><h3><a href="/poker/flush-and-redraw/">The flush arrives. What can still change?</a></h3>'''+cards('Ah Jh','Lab 02 focal hand')+'''<p>Follow a face-up hand across the streets. Count the possible rivers and check what changes when the opponent holds a different hand.</p><p class="lab-skill"><strong>Leave with:</strong> an exact remaining-card count with its information set stated.</p></article>
<article class="lab-series-card"><p class="reader-eyebrow">03 / Read the pots</p><h3><a href="/poker/side-pot-lab/">Three all-ins. Two pots.</a></h3>'''+cards('Ah Ad','Lab 03 shortest stack hand')+'''<p>Separate a three-way all-in into a main pot, side pot and refund. Then explain why the strongest hand does not receive every chip.</p><p class="lab-skill"><strong>Leave with:</strong> a complete chip ledger and a clear explanation of the result.</p></article>
</div></div></section>
<section class="section folio-row" aria-labelledby="labs-route"><div class="section-meta"><p class="section-label">Choose your route</p></div><div class="section-content prose"><h2 id="labs-route">Start with the question you care about.</h2><p><strong>New viewer:</strong> start with the runout case, then the pot case. Use <a href="/poker/hand-rankings/">hand rankings</a> whenever the name of the winning hand is unclear.</p><p><strong>Tournament student:</strong> begin with pot eligibility, then try the range case. A correct price is only useful when it refers to the right pot and the right assumptions.</p><p><strong>Vlog creator:</strong> work through any case and describe it in three sentences before reading its closing narration. Keep the action, your interpretation and the eventual result distinct.</p><h3>A small practice loop</h3><p>Read the setup. Make one prediction in your own private notes. Reveal the explanation. Name the exact mistake or uncertainty. Finally, change one input and try again. The changed examples check understanding rather than memory of the first answer.</p><p>No score is assigned and nothing records your answers. A missed example is a study question, not a verdict on your ability. Ordinary pageviews follow the existing <a href="/privacy/">privacy notice</a>.</p><div class="link-row"><a class="button" href="/poker/practice-room/">Try twelve shorter exercises</a><a class="text-link" href="/poker/library/">Browse the full guide library</a><a class="text-link" href="/poker/study/">Choose a study worksheet</a></div></div></section>'''
put('_source/poker/decision-labs.html',hub)
