#!/usr/bin/env python3
"""Build the public static site. Python 3.10+, no third-party dependencies."""
from __future__ import annotations
import argparse
import hashlib
import html
import json
from pathlib import Path
import re
import sys
from datetime import datetime, timezone
from email.utils import format_datetime
from xml.etree import ElementTree as ET
sys.path.insert(0, str(Path(__file__).resolve().parent))
from catalog import supplement
from poker_navigation import section_navigation
import poker_content
import poker_library
import poker_reading
import poker_experience
import poker_resources
import poker_collections
import poker_finder
import poker_reference
import poker_quality

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / '_source'
MARKER = '<!-- Generated by _scripts/build.py; edit _source files. -->'
TOKEN = re.compile(r'\$\{([a-z_]+)\}')


def text(value: object) -> str:
    return html.escape(str(value), quote=True)


def fill(template: str, values: dict) -> str:
    def replace(match):
        key = match.group(1)
        if key not in values:
            raise ValueError(f'Unknown template variable: {key}')
        return str(values[key])
    return TOKEN.sub(replace, template)


def output_path(route: str) -> Path:
    if not isinstance(route, str) or not re.fullmatch(r'/(?:[a-z0-9-]+/)*|/[a-z0-9-]+\.html', route):
        raise ValueError(f'Invalid page route: {route}')
    relative = route.lstrip('/')
    return Path(relative + 'index.html' if route.endswith('/') else relative)


def date_value(value: str) -> datetime:
    if not isinstance(value, str) or not re.fullmatch(r'\d{4}-\d{2}-\d{2}', value):
        raise ValueError('Dates must use YYYY-MM-DD')
    return datetime.strptime(value, '%Y-%m-%d').replace(tzinfo=timezone.utc)


def date_label(value: str) -> str:
    dt = date_value(value)
    return f'{dt.strftime("%B")} {dt.day}, {dt.year}'


def public_pages() -> list[dict]:
    """One manifest for rendering, link tests, sitemaps, and live verification."""
    base = json.loads((ROOT / '_source/pages.json').read_text(encoding='utf-8'))
    return base + poker_content.manifest(poker_content.load(ROOT))


def build_outputs() -> dict[Path, str]:
    site = json.loads((SOURCE / 'site.json').read_text(encoding='utf-8'))
    catalog = poker_content.load(ROOT)
    pages = public_pages()
    reader_entries = poker_library.load(ROOT, pages)
    poker_entries = {e['slug']: e for e in catalog['entries']}
    if len({p['path'] for p in pages}) != len(pages) or len({p['id'] for p in pages}) != len(pages):
        raise ValueError('Page routes and IDs must be unique')
    for p in pages:
        output_path(p['path'])
        if p.get('note') or p.get('poker_guide'):
            date_value(p['date'])
        if p.get('updated'):
            updated = date_value(p['updated'])
            if (p.get('note') or p.get('poker_guide')) and updated < date_value(p['date']):
                raise ValueError('An update cannot precede publication')
        if p.get('revision') and not p.get('updated'):
            raise ValueError('Substantive revisions need an explicit update date')
    notes = sorted((p for p in pages if p.get('note')), key=lambda p: (p['date'], p['id']), reverse=True)
    selection = json.loads((SOURCE / 'selection.json').read_text(encoding='utf-8'))
    order = selection['note_order']
    by_id = {p['id']: p for p in notes}
    if len(order) != len(set(order)) or set(order) != set(by_id):
        raise ValueError('Reading order must contain every public note exactly once')
    template = (SOURCE / 'layout.html').read_text(encoding='utf-8')
    articles = []
    for p in [by_id[slug] for slug in order]:
        articles.append(f'<article class="note-entry"><p class="note-category">{text(p["kicker"])}</p>'
                        f'<h3><a href="{text(p["path"])}">{text(p["title"])}</a></h3>'
                        f'<p>{text(p["description"])}</p></article>')
    values = {k: text(v) for k, v in site.items()}
    values['notes_list'] = '<div class="notes-list">' + '\n'.join(articles) + '</div>'
    values.update(supplement(ROOT, notes))
    values.update(poker_content.supplement(catalog, ROOT))
    values.update(poker_experience.supplement(catalog))
    resource_entries = poker_resources.load(ROOT)
    collections = poker_collections.load(ROOT, resource_entries, pages)
    values.update(poker_resources.supplement(resource_entries))
    values.update(poker_quality.supplement(resource_entries))
    values.update(poker_collections.supplement(collections, resource_entries))
    values.update(poker_library.supplement(reader_entries))
    values.update(poker_finder.render(poker_finder.entries(ROOT, pages, reader_entries, resource_entries)))
    values.update(poker_reference.supplement())
    # The on-page and printable previews use the exact downloadable blank files.
    for slug in ("poker-event-planner", "poker-hand-capture", "poker-resource-check"):
        values[slug.replace("-", "_")] = text((ROOT / "downloads" / (slug + ".md")).read_text(encoding="utf-8"))
    values['hubs_css_version'] = hashlib.sha256((ROOT / 'assets/hubs.css').read_bytes()).hexdigest()[:12]
    values['site_css_version'] = hashlib.sha256((ROOT / 'assets/site.css').read_bytes()).hexdigest()[:12]
    featured = by_id[selection['featured_note']]
    values.update({'featured_note_title': text(featured['title']), 'featured_note_url': text(featured['path']), 'featured_note_description': text(featured['description'])})
    outputs = {}
    for p in pages:
        if p.get('poker_entry'):
            body = poker_content.render(poker_entries[p['poker_entry']], catalog)
        else:
            source = (SOURCE / p['source']).resolve()
            if not source.is_relative_to(SOURCE.resolve()):
                raise ValueError('Content sources must remain within _source')
            body = fill(source.read_text(encoding='utf-8'), values)
        section = p.get('section') or ('notes' if p.get('note') else p['id'])
        nav = ''.join(f'<li><a href="/{name}/"' + ((' aria-current="page"' if p['path'] == '/' + name + '/' else ' aria-current="location"') if section == name else '')
                      + f'>{label}</a></li>' for name, label in [('technology', 'Technology'), ('poker', 'Poker'), ('creative', 'Creative Work'), ('about', 'About'), ('contact', 'Contact')])
        canonical = site['url'] + p['path']
        header = ''
        extra = '<meta name="robots" content="noindex, follow">' if p.get('noindex') else ''
        if p['id'] != 'home':
            heading = '<a href="/notes/" class="breadcrumb">All notes</a>' if p.get('note') else ''
            heading += f'<p class="page-kicker">{text(p["kicker"])}</p><h1 class="page-title">{text(p["title"])}</h1>'
            if p.get('note'):
                heading += f'<p class="note-meta">Published <time datetime="{p["date"]}">{date_label(p["date"])}</time> · Nolan Kido</p>'
                revision = ''
                if p.get('revision'):
                    revision = f'<p class="editorial-note"><strong>Revision, <time datetime="{p["updated"]}">{date_label(p["updated"])}</time>:</strong> {text(p["revision"])}</p>'
                body = ('    <article class="note-article" aria-label="Note">\n'
                        f'      <header class="page-hero shell">{heading}</header>\n'
                        f'      <div class="article-body shell prose">{body}{revision}'
                        '<p class="editorial-note">Prepared with AI assistance. Worked scenarios are fictional; research is linked where used. These essays do not describe private projects or personal events.</p>'
                        '<nav class="article-navigation" aria-label="After the note"><a href="/notes/">All notes</a>'
                        '<a href="/contact/">Send a thought or correction</a></nav></div>\n    </article>')
                extra += f'\n  <meta property="article:published_time" content="{p["date"]}">'
                if p.get('updated'):
                    extra += f'\n  <meta property="article:modified_time" content="{p["updated"]}">'
            else:
                header = f'    <section class="page-hero shell">{heading}</section>'
        schema = {'@context': 'https://schema.org', '@type': 'WebPage', 'name': p['seo_title'], 'url': canonical,
                  'description': p['description'], 'isPartOf': {'@type': 'WebSite', 'name': site['name'], 'url': site['url'] + '/'}}
        if p['id'] == 'home':
            schema['about'] = {'@type': 'Person', 'name': site['name'], 'url': site['url'] + '/'}
        if p.get('note'):
            schema.update({'@type': 'Article', 'headline': p['title'], 'datePublished': p['date'],
                           'author': {'@type': 'Person', 'name': site['name'], 'url': site['url'] + '/about/'}})
        if p.get('updated'):
            schema['dateModified'] = p['updated']
        if p['path'].startswith('/poker/'):
            poker_version = hashlib.sha256((ROOT / 'assets/poker.css').read_bytes()).hexdigest()[:12]
            extra += f'\n  <link rel="stylesheet" href="/assets/poker.css?v={poker_version}">'
            extra += '\n  <link rel="alternate" type="application/rss+xml" title="Nolan Kido Poker" href="/poker/feed.xml">'
            if p.get('poker_entry') or p.get('poker_guide'):
                schema.update({'@type': 'Article', 'headline': p['title'], 'datePublished': p['date'],
                               'author': {'@type': 'Person', 'name': site['name'], 'url': site['url'] + '/about/'}})
                extra += f'\n  <meta property="article:published_time" content="{p["date"]}">'
                if p.get('updated'):
                    extra += f'\n  <meta property="article:modified_time" content="{p["updated"]}">'
        if p['id'] == 'contact':
            contact_version = hashlib.sha256((ROOT / 'assets/contact.js').read_bytes()).hexdigest()[:12]
            extra += f'\n  <script src="/assets/contact.js?v={contact_version}" defer></script>'
        if p['path'].startswith('/poker/'):
            reader_version = hashlib.sha256((ROOT / 'assets/poker-reader.css').read_bytes()).hexdigest()[:12]
            extra += f'\n  <link rel="stylesheet" href="/assets/poker-reader.css?v={reader_version}">'
            if p['id'] == 'poker-tournament-checklists':
                sheets_version = hashlib.sha256((ROOT / 'assets/poker-fieldguide.css').read_bytes()).hexdigest()[:12]
                extra += f'\n  <link rel="stylesheet" href="/assets/poker-fieldguide.css?v={sheets_version}">'
            if p['id'] == 'poker-resources':
                resources_css_version = hashlib.sha256((ROOT / 'assets/poker-resources.css').read_bytes()).hexdigest()[:12]
                extra += f'\n  <link rel="stylesheet" href="/assets/poker-resources.css?v={resources_css_version}">'
                resources_version = hashlib.sha256((ROOT / 'assets/poker-resources.js').read_bytes()).hexdigest()[:12]
                extra += f'\n  <script defer src="/assets/poker-resources.js?v={resources_version}"></script>'
            if p['id'] == 'poker-study-calculators':
                for asset, kind in [('poker-study-tools.css', 'style'), ('poker-study-tools.js', 'script')]:
                    version = hashlib.sha256((ROOT / 'assets' / asset).read_bytes()).hexdigest()[:12]
                    extra += (f'\n  <link rel="stylesheet" href="/assets/{asset}?v={version}">' if kind == 'style' else f'\n  <script defer src="/assets/{asset}?v={version}"></script>')
            if p['id'] == 'poker-find':
                for asset, kind in [('poker-finder.css', 'style'), ('poker-finder.js', 'script')]:
                    version = hashlib.sha256((ROOT / 'assets' / asset).read_bytes()).hexdigest()[:12]
                    extra += (f'\n  <link rel="stylesheet" href="/assets/{asset}?v={version}">' if kind == 'style'
                              else f'\n  <script defer src="/assets/{asset}?v={version}"></script>')
            if p['id'] == 'poker-library':
                library_version = hashlib.sha256((ROOT / 'assets/poker-library.js').read_bytes()).hexdigest()[:12]
                extra += f'\n  <script defer src="/assets/poker-library.js?v={library_version}"></script>'
            reader_meta = poker_library.reader_meta(p, reader_entries)
            if reader_meta:
                header = header.replace('</section>', reader_meta + poker_reading.section_outline(body) + '</section>', 1)
                body += poker_library.related(p, reader_entries)
        if p['path'].startswith('/poker/') and not p.get('poker_entry') and p['path'] != '/poker/':
            body += poker_experience.related_work(catalog, p['path'])
        data = {**values, 'body': body, 'primary_nav': nav, 'section_nav': section_navigation(p), 'page_header': header, 'page_id': text(p['id']),
                'seo_title': text(p['seo_title']), 'description': text(p['description']), 'canonical': text(canonical),
                'og_type': 'article' if p.get('note') or p.get('poker_entry') or p.get('poker_guide') else 'website', 'extra_head': extra,
                'structured_data': json.dumps(schema, ensure_ascii=False).replace('<', '\\u003c')}
        rendered = fill(template, data).replace('<html lang="en">', f'<html lang="en">\n{MARKER}', 1)
        outputs[output_path(p['path'])] = rendered

    ET.register_namespace('atom', 'http://www.w3.org/2005/Atom')
    rss = ET.Element('rss', {'version': '2.0'})
    channel = ET.SubElement(rss, 'channel')
    for key, value in [('title', 'Nolan Kido Notes'), ('link', site['url'] + '/notes/'),
                       ('description', 'Worked explanations and reflections on tools, decisions, learning, and creative work.'), ('language', 'en-us')]:
        ET.SubElement(channel, key).text = value
    ET.SubElement(channel, '{http://www.w3.org/2005/Atom}link', {'href': site['url'] + '/feed.xml', 'rel': 'self', 'type': 'application/rss+xml'})
    for p in notes:
        item = ET.SubElement(channel, 'item')
        for key, value in [('title', p['title']), ('link', site['url'] + p['path']), ('description', p['description'])]:
            ET.SubElement(item, key).text = value
        ET.SubElement(item, 'guid', {'isPermaLink': 'true'}).text = site['url'] + p['path']
        ET.SubElement(item, 'pubDate').text = format_datetime(date_value(p['date']), usegmt=True)
    ET.indent(rss, space='  ')
    outputs[Path('feed.xml')] = '<?xml version="1.0" encoding="utf-8"?>\n' + ET.tostring(rss, encoding='unicode') + '\n'
    sitemap = ET.Element('urlset', {'xmlns': 'http://www.sitemaps.org/schemas/sitemap/0.9'})
    for p in pages:
        if not p.get('noindex'):
            item = ET.SubElement(sitemap, 'url')
            ET.SubElement(item, 'loc').text = site['url'] + p['path']
            if p.get('updated') or p.get('date'):
                ET.SubElement(item, 'lastmod').text = p.get('updated', p.get('date'))
    ET.indent(sitemap, space='  ')
    outputs[Path('sitemap.xml')] = '<?xml version="1.0" encoding="utf-8"?>\n' + ET.tostring(sitemap, encoding='unicode') + '\n'
    outputs.update(poker_collections.exports(resource_entries))
    outputs.update(poker_reference.exports())
    outputs[Path('poker/feed.xml')] = poker_content.feed(pages, site['url'])
    outputs[Path('nolan-kido.vcf')] = 'BEGIN:VCARD\nVERSION:3.0\nFN:Nolan Kido\nN:Kido;Nolan;;;\nURL:https://nolankido.com/\nEND:VCARD\n'
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if committed pages differ from source')
    args = parser.parse_args()
    try:
        outputs = build_outputs()
        differences = []
        # A removed guide or hub can remain publishable just like an old episode.
        # Refuse all stale generated Poker HTML before writing any build outputs.
        # Manual pages and other sections remain outside this ownership check.
        for existing in sorted((ROOT / 'poker').rglob('*.html')):
            if existing.relative_to(ROOT) not in outputs and MARKER in existing.read_text(encoding='utf-8'):
                raise ValueError('Orphaned poker page: ' + str(existing.relative_to(ROOT)) + '. Review and remove the stale generated file before release.')
        for relative, content in outputs.items():
            target = ROOT / relative
            if not target.exists() or target.read_text(encoding='utf-8') != content:
                differences.append(str(relative))
                if not args.check:
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_text(content, encoding='utf-8', newline='')
        if args.check and differences:
            print('Rebuild required: ' + ', '.join(differences), file=sys.stderr)
            return 1
        print(f'{len(outputs)} generated files {"checked" if args.check else "built"}; {len(differences)} changes.')
        return 0
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f'Build failed: {exc}', file=sys.stderr)
        return 1

if __name__ == '__main__':
    raise SystemExit(main())
